in:
  type: file
  path_prefix: example/data.tsv
  parser:
    type: csv
    delimiter: "\t"
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: time,  type: timestamp, format: "%Y-%m-%d"}
      - {name: id, type: long}
      - {name: name, type: string}
      - {name: score, type: double}
      - {name: json_payload, type: string}

filters:
  - type: expand_json
    json_column_name: json_payload
    root: "$."
    expanded_columns:
      - {name: "phone_numbers", path: "phone_numbers", type: string}
      - {name: "app", path: "app_id", path: "", type: long}
      - {name: "point", path: "point", type: double}
      - {name: "created_at", path: "created_at", type: timestamp, format: "%Y-%m-%d"}
      - {name: "anniversary_et", path: "profile.anniversary.et", type: string}
      - {name: "anniversary", path: "profile.anniversary", type: string}
      - {name: "like_words_1", path: "profile.like_words[1]", type: string}
      - {name: "like_words_2", path: "profile.like_words[2]", type: string}
      - {name: "like_words", path: "profile.like_words", type: string}

out:
  type: stdout

